version: '3'
services:
  python:
    build: .
    container_name: usemecav
    volumes:
      - ./start.sh:/start.sh
      - ./app:/app
    environment:
      VIDEO_ID: pmTQqhpHAHs
    command:
      sh /start.sh